language: ruby
sudo: false
rvm: 2.4.0
cache:
  bundler: true
# Notifications, used by our Gitter channel.
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9eef19829de6aa749075
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
