auto: true
server: true
markdown: kramdown
permalink: date
pygments: true

downloads:
  source:
    - name: Ruby 1.9.2-p290
      url: http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p290.tar.gz
      md5: 604da71839a6ae02b5b5b5e1b792d5eb
      comment: Stable Version (_recommended_)
    - name: Ruby 1.9.3 preview1
      url: http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-preview1.tar.gz
      md5: 0f0220be4cc7c51a82c1bd8f6a0969f3
    - name: Stable Snapshot
      url: http://ftp.ruby-lang.org/pub/ruby/ruby-1.9-stable.tar.gz
      comment: |
        This is tar&#8217;ed and gzip&#8217;ed file of the latest stable SVN.
        It should be better than the last stable release.
    - name: Nightly Snapshot
      url: http://ftp.ruby-lang.org/pub/ruby/snapshot.tar.gz
      comment: |
        This is tar&#8217;ed and gzip&#8217;ed file of the latest SVN.
        It may contain unfixed problems.

  windows:
    - name: Ruby 1.8.6-p398 RubyInstaller
      url: http://rubyforge.org/frs/download.php/71066/rubyinstaller-1.8.6-p398.exe
      md5: 233d6b3ddc4c61436b075b51254cd138
      comment: Stable version
    - name: Ruby 1.8.7-p334 RubyInstaller
      url: http://rubyforge.org/frs/download.php/74293/rubyinstaller-1.8.7-p334.exe
      md5: 64e30e63e16028282fcfe3ec57b561dc
      comment: Stable version (_recommended_)
    - name: Ruby 1.9.1-p430 RubyInstaller
      url: http://rubyforge.org/frs/download.php/72075/rubyinstaller-1.9.1-p430.exe
      md5: 86ac589a955898c3163b161d81750a05
      comment: Stable version
    - name: Ruby 1.9.2-p180 RubyInstaller
      url: http://rubyforge.org/frs/download.php/74298/rubyinstaller-1.9.2-p180.exe
      md5: 2c94aef50987416d64c85a4ea0fa428b
      comment: Stable version (_recommended_)
    - name: Ruby 1.8.7-p249 Binary
      url: http://ftp.ruby-lang.org/pub/ruby/binaries/mswin32/ruby-1.8.7-p249-i386-mswin32.zip
      md5: 4fd37b0b4b21a042cae7f5f0a8daad16
      comment: Stable version
    - name: Ruby 1.9.1-p378 Binary
      url: http://ftp.ruby-lang.org/pub/ruby/binaries/mswin32/ruby-1.9.1-p378-i386-mswin32.zip
      md5: 7d14a918cc8d243d3e2c409aff41f454
      comment: Stable version

top_projects:
  - name: FLVTool2
    url: http://rubyforge.org/projects/flvtool2/
    description: |
      FLVTool2 is a manipulation tool for Macromedia Flash Video files (FLV).
      It can calculate a lot of meta data, insert an onMetaData tag, cut FLV
      files, add cue points (onCuePoint), show the FLV structure and print
      meta data information in XML or YAML.

  - name: Ruby Enterprise Edition
    url: http://rubyforge.org/projects/emm-ruby/
    description: |
      Ruby Enterprise Edition is a branch of Ruby, which includes an enhanced
      garbage collector and developer tools. This allows one to reduce memory
      usage of Ruby on Rails applications by 33% on average.

  - name: SQLite-Ruby
    url: http://rubyforge.org/projects/sqlite-ruby/
    description: |
      A Ruby interface for the SQLite database engine.

  - name: Ruby/DBI
    url: http://rubyforge.org/projects/ruby-dbi/
    description: |
      Ruby/DBI develops a database independent interface for accessing
      databases - similar to Perl's DBI.

  - name: Watir
    url: http://rubyforge.org/projects/wtr/
    description: |
      Watir is a testing tool for automating browser-based tests of web
      applications. It is a Ruby library that works with Internet Explorer
      and Firefox.


# Localization

credits:
  en: |
    This website was generated with Ruby using <a href="http://www.jekyllrb.com/">Jekyll</a>.
    It is proudly maintained by <a href="http://rubyidentity.org">members of the Ruby community</a>.
    Please contact our <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
    for questions or comments concerning this website.
  de: |
    Diese Webseite wurde mit Ruby unter Verwendung von <a href="http://www.jekyllrb.com/">Jekyll</a> erstellt.
    Sie wird mit Stolz von <a href="http://rubyidentity.org">Mitgliedern der Ruby-Community</a> gepflegt.
    Bei Fragen oder Kommentaren, die diese Seite betreffen, kontaktieren Sie bitte
    unseren <a href="mailto:webmaster@ruby-lang.org">Webmaster</a> (in Englisch).
  es: |
    Este sitio web está desarrollado con Ruby y <a href="http://www.jekyllrb.com/">Jekyll</a>.
    Es orgullosamente mantenido por <a href="http://rubyidentity.org">miembros de la comunidad Ruby</a>.
    Por favor contacta a nuestro <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
    si tienes preguntas o comentarios al respecto del sitio web.
  fr: |
    Ce site est propulsé par Ruby et <a href="http://www.jekyllrb.com/">Jekyll</a>.
    Il est fièrement maintenu par des <a href="http://rubyidentity.org">membres de la communauté Ruby</a>.
    Veuillez contacter notre <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
    pour toute question ou tout commentaire le concernant.
  it: |
    Questo sito è stato sviluppato con Ruby e <a href="http://www.jekyllrb.com/">Jekyll</a>.
    È curato con dedizione dai <a href="http://rubyidentity.org">membri della comunità di Ruby</a>.
    Puoi contattare il nostro <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
    per domande e commenti riguardanti questo sito.

locales:
  sitelinks:
    en:
      - name: Downloads
        url:  downloads
      - name: Documentation
        url:  documentation
      - name: Libraries
        url:  libraries
      - name: Community
        url:  community
      - name: News
        url:  news
      - name: Security
        url:  security
      - name: About Ruby
        url:  about
    de:
      - name: Downloads
        url:  downloads
      - name: Dokumentation
        url:  documentation
      - name: Bibliotheken
        url:  libraries
      - name: Community
        url:  community
      - name: Neuigkeiten
        url:  news
      # - name: Sicherheit
      #   url:  security
      - name: Über Ruby
        url:  about
    es:
      - name: Descargas
        url:  downloads
      - name: Documentación
        url:  documentation
      - name: Bibliotecas
        url:  libraries
      - name: Comunidad
        url:  community
      - name: Noticias
        url:  news
      # - name: Seguridad
      #   url:  security
      - name: Acerca de Ruby
        url:  about
    fr:
      - name: Téléchargements
        url:  downloads
      - name: Documentation
        url:  documentation
      - name: Bibliothèques
        url:  libraries
      - name: Communauté
        url:  community
      - name: Actualités
        url:  news
      - name: Sécurité
        url:  security
      - name: À propos de Ruby
        url:  about
    id:
      - name: Download
        url: downloads
      - name: Dokumentasi
        url: documentation
      - name: Library
        url: libraries
      - name: Komunitas
        url: community
      - name: Berita
        url: news
      - name: Tentang Ruby
        url: about
    it:
      - name: Scarica
        url:  downloads
      - name: Documentazione
        url:  documentation
      - name: Librerie
        url:  libraries
      - name: Comunità
        url:  community
      - name: Notizie
        url:  news
      - name: Sicurezza
        url:  security
      - name: A proposito di Ruby
        url:  about
    ja:
      - name: ダウンロード
        url: downloads
      - name: ドキュメント
        url: documentation
      - name: ライブラリ
        url: libraries
      - name: コミュニティ
        url: community
      - name: コア開発
        url: dev
      - name: ニュース
        url: news
      - name: セキュリティ
        url: security
      - name: Rubyとは
        url: about
    ko:
      - name: 다운로드
        url: downloads
      - name: 문서
        url: documentation
      - name: 라이브러리
        url: libraries
      - name: 커뮤니티
        url: community
      - name: 뉴스
        url: news
      - name: 보안이슈
        url: security
      - name: 루비에 대해서
        url: about
    pl:
      - name: Pobierz
        url: downloads
      - name: Dokumentacja
        url: dokumentacja
      - name: Biblioteki
        url: libraries
      - name: Społeczność
        url: spolecznosc
      - name: Wiadomości
        url: news
      - name: O języku Ruby
        url: about
    pt:
      - name:  Downloads
        url: downloads
      - name: Documentação
        url: documentacao
      - name: Módulos
        url: bibliotecas
      - name: Comunidade
        url: comunidade
      - name: Notícias
        url: noticias-recentes
      - name: Sobre Ruby
        url: sobre-o-ruby
    tr:
      - name: İndirin
        url: downloads
      - name: Belgeler
        url: documentation
      - name: Kütüphaneler
        url: libraries
      - name: Topluluk
        url: community
      - name: Haberler
        url: news
      - name: Güvenlik
        url: security
      - name: Ruby Hakkında
        url: about
    zh_cn:
      - name: 下载
        url: downloads
      - name: 文档
        url: documentation
      - name: 资源库
        url: libraries
      - name: 社区
        url: community
      - name: 新闻
        url: news
      - name: 安全
        url: security
      - name: 关于 Ruby
        url: about
    zh_TW:
      - name: 下載安裝
        url: downloads
      - name: 文件
        url: documentation
      - name: 函式庫
        url: libraries
      - name: 社群
        url: community
      - name: 新聞
        url: news
      - name: 安全
        url: security
      - name: 關於 Ruby
        url: about
