markdown: kramdown
permalink: pretty
highlighter: rouge

timezone: UTC

kramdown:
  auto_ids: false

exclude:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - README.md
  - unicorn.rb
  - lib
  - test
  - vendor

url: https://www.ruby-lang.org

license:
  url: /en/about/license.txt

svn:
  stable:
    version: 2.6
    branch:  ruby_2_6
  previous:
    version: 2.5
    branch:  ruby_2_5
  old:
    version: 2.4
    branch:  ruby_2_4
