markdown: kramdown
permalink: pretty
highlighter: rouge

timezone: UTC

kramdown:
  auto_ids: true  # Enable auto IDs for TOC links

include:
  - _headers

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - lib
  - test
  - vendor
  - tsconfig.json

url: https://www.ruby-lang.org

license:
  url: /en/about/license.txt

svn:
  stable:
    version: 2.6
    branch:  ruby_2_6
  previous:
    version: 2.5
    branch:  ruby_2_5
  old:
    version: 2.4
    branch:  ruby_2_4
