name: ci

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})

    strategy:
      matrix:
        ruby: ["3.2"]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Dump environment
        run: env | sort
      - name: Checkout ruby/www.ruby-lang.org
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1
      - name: Setup Ruby
        uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # v1.162.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Dump Ruby version
        run: ruby -v
      - name: Run tests
        run: bundle exec rake test
