name: ci

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})

    strategy:
      matrix:
        ruby: ["3.2"]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Dump environment
        run: env | sort
      - name: Checkout ruby/www.ruby-lang.org
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 1
      - name: Setup Ruby
        uses: ruby/setup-ruby@bc1dd263b68cb5626dbb55d5c89777d79372c484 # v1.151.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Dump Ruby version
        run: ruby -v
      - name: Run tests
        run: bundle exec rake test
