name: Create draft release

on:
  repository_dispatch:
    types:
      - release
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Ruby package to release'
        required: true
        default: '3.3.4'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'ruby/www.ruby-lang.org'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ruby/ruby
          path: ruby

      - uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c # v1.287.0
        with:
          ruby-version: 3.3.4

      - name: Generate draft release entry
        run: |
          ruby lib/draft-release.rb ${{ github.event.client_payload.version || github.event.inputs.version }}

      - name: Update data files
        run: |
          tool/format-release .. ${{ github.event.client_payload.version || github.event.inputs.version }} .
        working-directory: ruby

      - name: Cleanup ruby directory
        run: |
          rm -rf ruby

      - name: Create Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Create release for ${{ github.event.client_payload.version || github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.MATZBOT_AUTO_UPDATE_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.MATZBOT_AUTO_UPDATE_TOKEN }}
          branch: releases/${{ github.event.client_payload.version || github.event.inputs.version }}
          delete-branch: true
          title: "Create release for ${{ github.event.client_payload.version || github.event.inputs.version }}"
          body: "This is an automated pull request to create a release"
          draft: true
